/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppError = { 'saleNotFound' : SaleId } |
  { 'itemNotFound' : ItemId } |
  { 'emptyField' : string } |
  { 'invalidNumber' : string } |
  { 'invalidDate' : string } |
  { 'emptyOrder' : null } |
  {
    'insufficientStock' : {
      'itemId' : ItemId,
      'requested' : Qty,
      'available' : Qty,
    }
  };
export type AppResult = { 'ok' : ItemView } |
  { 'err' : AppError };
export type AppResult_1 = { 'ok' : SaleView } |
  { 'err' : AppError };
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type IsoDate = string;
export interface ItemEdit { 'hargaPokok' : Rupiah, 'ukuran' : string }
export type ItemId = bigint;
export interface ItemView {
  'id' : ItemId,
  'namaBarang' : string,
  'createdAt' : Timestamp,
  'hargaPokok' : Rupiah,
  'updatedAt' : Timestamp,
  'ukuran' : string,
  'stockMaster' : Qty,
}
export type Month = bigint;
export interface MonthlyProfit { 'month' : Month, 'laba' : bigint }
export interface NewItem {
  'namaBarang' : string,
  'hargaPokok' : Rupiah,
  'ukuran' : string,
  'stockMaster' : Qty,
}
export interface NewSale { 'tanggal' : IsoDate, 'lines' : Array<NewSaleLine> }
export interface NewSaleLine {
  'itemId' : [] | [ItemId],
  'hargaJual' : Rupiah,
  'namaBarang' : [] | [string],
  'qtyOrder' : Qty,
  'hargaPokok' : [] | [Rupiah],
  'ukuran' : [] | [string],
}
export interface ProfitRow {
  'saleId' : SaleId,
  'hargaJual' : Rupiah,
  'namaBarang' : string,
  'tanggal' : IsoDate,
  'qtyOrder' : Qty,
  'laba' : bigint,
  'hargaPokok' : Rupiah,
  'ukuran' : string,
}
export interface ProfitSummary {
  'rows' : Array<ProfitRow>,
  'totalLaba' : bigint,
  'untung' : boolean,
}
export type Qty = bigint;
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Rupiah = bigint;
export type SaleId = bigint;
export interface SaleLine {
  'jumlah' : Rupiah,
  'itemId' : [] | [ItemId],
  'hargaJual' : Rupiah,
  'namaBarang' : string,
  'qtyOrder' : Qty,
  'hargaPokok' : Rupiah,
  'ukuran' : string,
  'manual' : boolean,
}
export interface SaleView {
  'id' : SaleId,
  'total' : Rupiah,
  'tanggal' : IsoDate,
  'createdAt' : Timestamp,
  'lines' : Array<SaleLine>,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type Year = bigint;
export interface YearlyProfit {
  'year' : Year,
  'totalLaba' : bigint,
  'months' : Array<MonthlyProfit>,
}
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a master barang. Requires a signed-in caller.
   */
  'createItem' : ActorMethod<[NewItem], AppResult>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Static Markdown documentation of this backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch one master barang. Requires a signed-in caller.
   */
  'getItem' : ActorMethod<[ItemId], [] | [ItemView]>,
  /**
   * / Monthly profit series for a year, ordered January..December.
   * / Requires a signed-in caller.
   */
  'getMonthlyProfit' : ActorMethod<[Year], YearlyProfit>,
  /**
   * / Profit/loss report rows and totals, optionally filtered by year and month.
   * / Requires a signed-in caller.
   */
  'getProfitReport' : ActorMethod<[[] | [Year], [] | [Month]], ProfitSummary>,
  /**
   * / Fetch one penjualan with its lines. Requires a signed-in caller.
   */
  'getSale' : ActorMethod<[SaleId], [] | [SaleView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List every master barang. Requires a signed-in caller.
   */
  'listItems' : ActorMethod<[], Array<ItemView>>,
  /**
   * / List every penjualan, newest first. Requires a signed-in caller.
   */
  'listSales' : ActorMethod<[], Array<SaleView>>,
  /**
   * / Save a penjualan and decrement Stock Master. Requires a signed-in caller.
   */
  'saveSale' : ActorMethod<[NewSale], AppResult_1>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Search master barang by name (case-insensitive substring). Requires a signed-in caller.
   */
  'searchItems' : ActorMethod<[string], Array<ItemView>>,
  /**
   * / Edit a master barang's `ukuran` and `hargaPokok`. Requires a signed-in caller.
   */
  'updateItem' : ActorMethod<[ItemId, ItemEdit], AppResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];