/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Rupiah = IDL.Nat;
export const Qty = IDL.Nat;
export const NewItem = IDL.Record({
  'namaBarang' : IDL.Text,
  'hargaPokok' : Rupiah,
  'ukuran' : IDL.Text,
  'stockMaster' : Qty,
});
export const ItemId = IDL.Nat;
export const Timestamp = IDL.Nat;
export const ItemView = IDL.Record({
  'id' : ItemId,
  'namaBarang' : IDL.Text,
  'createdAt' : Timestamp,
  'hargaPokok' : Rupiah,
  'updatedAt' : Timestamp,
  'ukuran' : IDL.Text,
  'stockMaster' : Qty,
});
export const SaleId = IDL.Nat;
export const AppError = IDL.Variant({
  'saleNotFound' : SaleId,
  'itemNotFound' : ItemId,
  'emptyField' : IDL.Text,
  'invalidNumber' : IDL.Text,
  'invalidDate' : IDL.Text,
  'emptyOrder' : IDL.Null,
  'insufficientStock' : IDL.Record({
    'itemId' : ItemId,
    'requested' : Qty,
    'available' : Qty,
  }),
});
export const AppResult = IDL.Variant({ 'ok' : ItemView, 'err' : AppError });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Year = IDL.Nat;
export const Month = IDL.Nat;
export const MonthlyProfit = IDL.Record({ 'month' : Month, 'laba' : IDL.Int });
export const YearlyProfit = IDL.Record({
  'year' : Year,
  'totalLaba' : IDL.Int,
  'months' : IDL.Vec(MonthlyProfit),
});
export const IsoDate = IDL.Text;
export const ProfitRow = IDL.Record({
  'saleId' : SaleId,
  'hargaJual' : Rupiah,
  'namaBarang' : IDL.Text,
  'tanggal' : IsoDate,
  'qtyOrder' : Qty,
  'laba' : IDL.Int,
  'hargaPokok' : Rupiah,
  'ukuran' : IDL.Text,
});
export const ProfitSummary = IDL.Record({
  'rows' : IDL.Vec(ProfitRow),
  'totalLaba' : IDL.Int,
  'untung' : IDL.Bool,
});
export const SaleLine = IDL.Record({
  'jumlah' : Rupiah,
  'itemId' : IDL.Opt(ItemId),
  'hargaJual' : Rupiah,
  'namaBarang' : IDL.Text,
  'qtyOrder' : Qty,
  'hargaPokok' : Rupiah,
  'ukuran' : IDL.Text,
  'manual' : IDL.Bool,
});
export const SaleView = IDL.Record({
  'id' : SaleId,
  'total' : Rupiah,
  'tanggal' : IsoDate,
  'createdAt' : Timestamp,
  'lines' : IDL.Vec(SaleLine),
});
export const NewSaleLine = IDL.Record({
  'itemId' : IDL.Opt(ItemId),
  'hargaJual' : Rupiah,
  'namaBarang' : IDL.Opt(IDL.Text),
  'qtyOrder' : Qty,
  'hargaPokok' : IDL.Opt(Rupiah),
  'ukuran' : IDL.Opt(IDL.Text),
});
export const NewSale = IDL.Record({
  'tanggal' : IsoDate,
  'lines' : IDL.Vec(NewSaleLine),
});
export const AppResult_1 = IDL.Variant({ 'ok' : SaleView, 'err' : AppError });
export const ItemEdit = IDL.Record({
  'hargaPokok' : Rupiah,
  'ukuran' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createItem' : IDL.Func([NewItem], [AppResult], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItem' : IDL.Func([ItemId], [IDL.Opt(ItemView)], ['query']),
  'getMonthlyProfit' : IDL.Func([Year], [YearlyProfit], ['query']),
  'getProfitReport' : IDL.Func(
      [IDL.Opt(Year), IDL.Opt(Month)],
      [ProfitSummary],
      ['query'],
    ),
  'getSale' : IDL.Func([SaleId], [IDL.Opt(SaleView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listItems' : IDL.Func([], [IDL.Vec(ItemView)], ['query']),
  'listSales' : IDL.Func([], [IDL.Vec(SaleView)], ['query']),
  'saveSale' : IDL.Func([NewSale], [AppResult_1], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchItems' : IDL.Func([IDL.Text], [IDL.Vec(ItemView)], ['query']),
  'updateItem' : IDL.Func([ItemId, ItemEdit], [AppResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Rupiah = IDL.Nat;
  const Qty = IDL.Nat;
  const NewItem = IDL.Record({
    'namaBarang' : IDL.Text,
    'hargaPokok' : Rupiah,
    'ukuran' : IDL.Text,
    'stockMaster' : Qty,
  });
  const ItemId = IDL.Nat;
  const Timestamp = IDL.Nat;
  const ItemView = IDL.Record({
    'id' : ItemId,
    'namaBarang' : IDL.Text,
    'createdAt' : Timestamp,
    'hargaPokok' : Rupiah,
    'updatedAt' : Timestamp,
    'ukuran' : IDL.Text,
    'stockMaster' : Qty,
  });
  const SaleId = IDL.Nat;
  const AppError = IDL.Variant({
    'saleNotFound' : SaleId,
    'itemNotFound' : ItemId,
    'emptyField' : IDL.Text,
    'invalidNumber' : IDL.Text,
    'invalidDate' : IDL.Text,
    'emptyOrder' : IDL.Null,
    'insufficientStock' : IDL.Record({
      'itemId' : ItemId,
      'requested' : Qty,
      'available' : Qty,
    }),
  });
  const AppResult = IDL.Variant({ 'ok' : ItemView, 'err' : AppError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Year = IDL.Nat;
  const Month = IDL.Nat;
  const MonthlyProfit = IDL.Record({ 'month' : Month, 'laba' : IDL.Int });
  const YearlyProfit = IDL.Record({
    'year' : Year,
    'totalLaba' : IDL.Int,
    'months' : IDL.Vec(MonthlyProfit),
  });
  const IsoDate = IDL.Text;
  const ProfitRow = IDL.Record({
    'saleId' : SaleId,
    'hargaJual' : Rupiah,
    'namaBarang' : IDL.Text,
    'tanggal' : IsoDate,
    'qtyOrder' : Qty,
    'laba' : IDL.Int,
    'hargaPokok' : Rupiah,
    'ukuran' : IDL.Text,
  });
  const ProfitSummary = IDL.Record({
    'rows' : IDL.Vec(ProfitRow),
    'totalLaba' : IDL.Int,
    'untung' : IDL.Bool,
  });
  const SaleLine = IDL.Record({
    'jumlah' : Rupiah,
    'itemId' : IDL.Opt(ItemId),
    'hargaJual' : Rupiah,
    'namaBarang' : IDL.Text,
    'qtyOrder' : Qty,
    'hargaPokok' : Rupiah,
    'ukuran' : IDL.Text,
    'manual' : IDL.Bool,
  });
  const SaleView = IDL.Record({
    'id' : SaleId,
    'total' : Rupiah,
    'tanggal' : IsoDate,
    'createdAt' : Timestamp,
    'lines' : IDL.Vec(SaleLine),
  });
  const NewSaleLine = IDL.Record({
    'itemId' : IDL.Opt(ItemId),
    'hargaJual' : Rupiah,
    'namaBarang' : IDL.Opt(IDL.Text),
    'qtyOrder' : Qty,
    'hargaPokok' : IDL.Opt(Rupiah),
    'ukuran' : IDL.Opt(IDL.Text),
  });
  const NewSale = IDL.Record({
    'tanggal' : IsoDate,
    'lines' : IDL.Vec(NewSaleLine),
  });
  const AppResult_1 = IDL.Variant({ 'ok' : SaleView, 'err' : AppError });
  const ItemEdit = IDL.Record({ 'hargaPokok' : Rupiah, 'ukuran' : IDL.Text });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createItem' : IDL.Func([NewItem], [AppResult], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItem' : IDL.Func([ItemId], [IDL.Opt(ItemView)], ['query']),
    'getMonthlyProfit' : IDL.Func([Year], [YearlyProfit], ['query']),
    'getProfitReport' : IDL.Func(
        [IDL.Opt(Year), IDL.Opt(Month)],
        [ProfitSummary],
        ['query'],
      ),
    'getSale' : IDL.Func([SaleId], [IDL.Opt(SaleView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listItems' : IDL.Func([], [IDL.Vec(ItemView)], ['query']),
    'listSales' : IDL.Func([], [IDL.Vec(SaleView)], ['query']),
    'saveSale' : IDL.Func([NewSale], [AppResult_1], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchItems' : IDL.Func([IDL.Text], [IDL.Vec(ItemView)], ['query']),
    'updateItem' : IDL.Func([ItemId, ItemEdit], [AppResult], []),
  });
};

export const init = ({ IDL }) => { return []; };