/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type AppError = {
    __kind__: "saleNotFound";
    saleNotFound: SaleId;
} | {
    __kind__: "itemNotFound";
    itemNotFound: ItemId;
} | {
    __kind__: "emptyField";
    emptyField: string;
} | {
    __kind__: "invalidNumber";
    invalidNumber: string;
} | {
    __kind__: "invalidDate";
    invalidDate: string;
} | {
    __kind__: "emptyOrder";
    emptyOrder: null;
} | {
    __kind__: "insufficientStock";
    insufficientStock: {
        itemId: ItemId;
        requested: Qty;
        available: Qty;
    };
};
export type AppResult = {
    __kind__: "ok";
    ok: ItemView;
} | {
    __kind__: "err";
    err: AppError;
};
export type AppResult_1 = {
    __kind__: "ok";
    ok: SaleView;
} | {
    __kind__: "err";
    err: AppError;
};
export interface Cell {
    value: Value;
    name: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type IsoDate = string;
export interface ItemEdit {
    hargaPokok: Rupiah;
    ukuran: string;
}
export type ItemId = bigint;
export interface ItemView {
    id: ItemId;
    namaBarang: string;
    createdAt: Timestamp;
    hargaPokok: Rupiah;
    updatedAt: Timestamp;
    ukuran: string;
    stockMaster: Qty;
}
export type Month = bigint;
export interface MonthlyProfit {
    month: Month;
    laba: bigint;
}
export interface NewItem {
    namaBarang: string;
    hargaPokok: Rupiah;
    ukuran: string;
    stockMaster: Qty;
}
export interface NewSale {
    tanggal: IsoDate;
    lines: Array<NewSaleLine>;
}
export interface NewSaleLine {
    itemId?: ItemId;
    hargaJual: Rupiah;
    namaBarang?: string;
    qtyOrder: Qty;
    hargaPokok?: Rupiah;
    ukuran?: string;
}
export interface ProfitRow {
    saleId: SaleId;
    hargaJual: Rupiah;
    namaBarang: string;
    tanggal: IsoDate;
    qtyOrder: Qty;
    laba: bigint;
    hargaPokok: Rupiah;
    ukuran: string;
}
export interface ProfitSummary {
    rows: Array<ProfitRow>;
    totalLaba: bigint;
    untung: boolean;
}
export type Qty = bigint;
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Rupiah = bigint;
export type SaleId = bigint;
export interface SaleLine {
    jumlah: Rupiah;
    itemId?: ItemId;
    hargaJual: Rupiah;
    namaBarang: string;
    qtyOrder: Qty;
    hargaPokok: Rupiah;
    ukuran: string;
    manual: boolean;
}
export interface SaleView {
    id: SaleId;
    total: Rupiah;
    tanggal: IsoDate;
    createdAt: Timestamp;
    lines: Array<SaleLine>;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export type Year = bigint;
export interface YearlyProfit {
    year: Year;
    totalLaba: bigint;
    months: Array<MonthlyProfit>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Create a master barang. Requires a signed-in caller.
     */
    createItem(input: NewItem): Promise<AppResult>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Static Markdown documentation of this backend's public API.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Fetch one master barang. Requires a signed-in caller.
     */
    getItem(id: ItemId): Promise<ItemView | null>;
    /**
     * / Monthly profit series for a year, ordered January..December.
     * / Requires a signed-in caller.
     */
    getMonthlyProfit(year: Year): Promise<YearlyProfit>;
    /**
     * / Profit/loss report rows and totals, optionally filtered by year and month.
     * / Requires a signed-in caller.
     */
    getProfitReport(year: Year | null, month: Month | null): Promise<ProfitSummary>;
    /**
     * / Fetch one penjualan with its lines. Requires a signed-in caller.
     */
    getSale(id: SaleId): Promise<SaleView | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List every master barang. Requires a signed-in caller.
     */
    listItems(): Promise<Array<ItemView>>;
    /**
     * / List every penjualan, newest first. Requires a signed-in caller.
     */
    listSales(): Promise<Array<SaleView>>;
    /**
     * / Save a penjualan and decrement Stock Master. Requires a signed-in caller.
     */
    saveSale(input: NewSale): Promise<AppResult_1>;
    schema(): Promise<string>;
    /**
     * / Search master barang by name (case-insensitive substring). Requires a signed-in caller.
     */
    searchItems(term: string): Promise<Array<ItemView>>;
    /**
     * / Edit a master barang's `ukuran` and `hargaPokok`. Requires a signed-in caller.
     */
    updateItem(id: ItemId, edit: ItemEdit): Promise<AppResult>;
}
import type { AppError as _AppError, AppResult as _AppResult, AppResult_1 as _AppResult_1, Cell as _Cell, Error as _Error, IsoDate as _IsoDate, ItemId as _ItemId, ItemView as _ItemView, Month as _Month, NewSale as _NewSale, NewSaleLine as _NewSaleLine, Qty as _Qty, Result as _Result, Result__1 as _Result__1, Rupiah as _Rupiah, SaleId as _SaleId, SaleLine as _SaleLine, SaleView as _SaleView, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value, Year as _Year } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createItem(arg0: NewItem): Promise<AppResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createItem(arg0);
                return from_candid_AppResult_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createItem(arg0);
            return from_candid_AppResult_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItem(arg0: ItemId): Promise<ItemView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItem(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItem(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyProfit(arg0: Year): Promise<YearlyProfit> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyProfit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyProfit(arg0);
            return result;
        }
    }
    async getProfitReport(arg0: Year | null, arg1: Month | null): Promise<ProfitSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfitReport(to_candid_opt_n20(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfitReport(to_candid_opt_n20(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getSale(arg0: SaleId): Promise<SaleView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSale(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSale(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listItems(): Promise<Array<ItemView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listItems();
            return result;
        }
    }
    async listSales(): Promise<Array<SaleView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSales();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSales();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveSale(arg0: NewSale): Promise<AppResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSale(to_candid_NewSale_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AppResult_1_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSale(to_candid_NewSale_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AppResult_1_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchItems(arg0: string): Promise<Array<ItemView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchItems(arg0);
            return result;
        }
    }
    async updateItem(arg0: ItemId, arg1: ItemEdit): Promise<AppResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItem(arg0, arg1);
                return from_candid_AppResult_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItem(arg0, arg1);
            return from_candid_AppResult_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppError_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppError): AppError {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_AppResult_1_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppResult_1): AppResult_1 {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_AppResult_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppResult): AppResult {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_SaleLine_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaleLine): SaleLine {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_SaleView_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaleView): SaleView {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ItemView]): ItemView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SaleView]): SaleView | null {
    return value.length === 0 ? null : from_candid_SaleView_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ItemId]): ItemId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n12(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n16(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SaleId;
    total: _Rupiah;
    tanggal: _IsoDate;
    createdAt: _Timestamp;
    lines: Array<_SaleLine>;
}): {
    id: SaleId;
    total: Rupiah;
    tanggal: IsoDate;
    createdAt: Timestamp;
    lines: Array<SaleLine>;
} {
    return {
        id: value.id,
        total: value.total,
        tanggal: value.tanggal,
        createdAt: value.createdAt,
        lines: from_candid_vec_n25(_uploadFile, _downloadFile, value.lines)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jumlah: _Rupiah;
    itemId: [] | [_ItemId];
    hargaJual: _Rupiah;
    namaBarang: string;
    qtyOrder: _Qty;
    hargaPokok: _Rupiah;
    ukuran: string;
    manual: boolean;
}): {
    jumlah: Rupiah;
    itemId?: ItemId;
    hargaJual: Rupiah;
    namaBarang: string;
    qtyOrder: Qty;
    hargaPokok: Rupiah;
    ukuran: string;
    manual: boolean;
} {
    return {
        jumlah: value.jumlah,
        itemId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.itemId)),
        hargaJual: value.hargaJual,
        namaBarang: value.namaBarang,
        qtyOrder: value.qtyOrder,
        hargaPokok: value.hargaPokok,
        ukuran: value.ukuran,
        manual: value.manual
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SaleView;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: SaleView;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_SaleView_n23(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n8(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ItemView;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: ItemView;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n8(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    saleNotFound: _SaleId;
} | {
    itemNotFound: _ItemId;
} | {
    emptyField: string;
} | {
    invalidNumber: string;
} | {
    invalidDate: string;
} | {
    emptyOrder: null;
} | {
    insufficientStock: {
        itemId: _ItemId;
        requested: _Qty;
        available: _Qty;
    };
}): {
    __kind__: "saleNotFound";
    saleNotFound: SaleId;
} | {
    __kind__: "itemNotFound";
    itemNotFound: ItemId;
} | {
    __kind__: "emptyField";
    emptyField: string;
} | {
    __kind__: "invalidNumber";
    invalidNumber: string;
} | {
    __kind__: "invalidDate";
    invalidDate: string;
} | {
    __kind__: "emptyOrder";
    emptyOrder: null;
} | {
    __kind__: "insufficientStock";
    insufficientStock: {
        itemId: ItemId;
        requested: Qty;
        available: Qty;
    };
} {
    return "saleNotFound" in value ? {
        __kind__: "saleNotFound",
        saleNotFound: value.saleNotFound
    } : "itemNotFound" in value ? {
        __kind__: "itemNotFound",
        itemNotFound: value.itemNotFound
    } : "emptyField" in value ? {
        __kind__: "emptyField",
        emptyField: value.emptyField
    } : "invalidNumber" in value ? {
        __kind__: "invalidNumber",
        invalidNumber: value.invalidNumber
    } : "invalidDate" in value ? {
        __kind__: "invalidDate",
        invalidDate: value.invalidDate
    } : "emptyOrder" in value ? {
        __kind__: "emptyOrder",
        emptyOrder: value.emptyOrder
    } : "insufficientStock" in value ? {
        __kind__: "insufficientStock",
        insufficientStock: value.insufficientStock
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SaleLine>): Array<SaleLine> {
    return value.map((x)=>from_candid_SaleLine_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SaleView>): Array<SaleView> {
    return value.map((x)=>from_candid_SaleView_n23(_uploadFile, _downloadFile, x));
}
function to_candid_NewSaleLine_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewSaleLine): _NewSaleLine {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_NewSale_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewSale): _NewSale {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Year | null): [] | [_Year] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Month | null): [] | [_Month] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tanggal: IsoDate;
    lines: Array<NewSaleLine>;
}): {
    tanggal: _IsoDate;
    lines: Array<_NewSaleLine>;
} {
    return {
        tanggal: value.tanggal,
        lines: to_candid_vec_n32(_uploadFile, _downloadFile, value.lines)
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    itemId?: ItemId;
    hargaJual: Rupiah;
    namaBarang?: string;
    qtyOrder: Qty;
    hargaPokok?: Rupiah;
    ukuran?: string;
}): {
    itemId: [] | [_ItemId];
    hargaJual: _Rupiah;
    namaBarang: [] | [string];
    qtyOrder: _Qty;
    hargaPokok: [] | [_Rupiah];
    ukuran: [] | [string];
} {
    return {
        itemId: value.itemId ? candid_some(value.itemId) : candid_none(),
        hargaJual: value.hargaJual,
        namaBarang: value.namaBarang ? candid_some(value.namaBarang) : candid_none(),
        qtyOrder: value.qtyOrder,
        hargaPokok: value.hargaPokok ? candid_some(value.hargaPokok) : candid_none(),
        ukuran: value.ukuran ? candid_some(value.ukuran) : candid_none()
    };
}
function to_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<NewSaleLine>): Array<_NewSaleLine> {
    return value.map((x)=>to_candid_NewSaleLine_n33(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
